 const axios = require("axios");

const fs = require("fs-extra");

const path = require("path");

const AdmZip = require("adm-zip");

const { execSync, exec } = require("child_process");
const net = require("net"); // 👈 Added for port discovery


// ─── Utility: Find Available Port ────────────────────────────────────────

function findFreePort(startPort) {
    return new Promise((resolve) => {
        const server = net.createServer();
        server.listen(startPort, () => {
            const { port } = server.address();
            server.close(() => resolve(port));
        });
        server.on('error', () => {
            resolve(findFreePort(startPort + 1));
        });
    });
}


// 👇 IMPORT YOUR INDEX BUILDER TO GET AST METADATA

const { index } = require("../services/indexBuilder"); 
const sseService = require("../services/sseService"); // 👈 Added for app-opening notifications


const TEMP_DIR = path.join(__dirname, "../../temp");


// ─── Step 1: The Tracing Templates ───────────────────────────────────────


const TRACING_CODE = `

const { NodeSDK } = require('@opentelemetry/sdk-node');

const { getNodeAutoInstrumentations } = require('@opentelemetry/auto-instrumentations-node');

const { OTLPTraceExporter } = require('@opentelemetry/exporter-trace-otlp-http');


const sdk = new NodeSDK({

  traceExporter: new OTLPTraceExporter({

    url: 'http://localhost:5000/api/shinkei/v1/traces',

  }),

  instrumentations: [

    getNodeAutoInstrumentations({

      '@opentelemetry/instrumentation-fs': { enabled: false }

    })

  ],

  serviceName: 'shinkei-dynamic-target',

});


sdk.start();

console.log('✅ Shinkei OTel SDK Active');

`;


const REQUIRE_HOOK_CODE = `
const Module = require('module');
const { trace } = require('@opentelemetry/api');
const fs = require('fs');
const path = require('path');

const originalRequire = Module.prototype.require;
const repoRoot = process.env.SHINKEI_REPO_ROOT;

// 🔥 Load the AST map generated by Shinkei Static Analysis
const astMapPath = path.join(__dirname, 'ast_map.json');
let functionMap = new Map();
if (fs.existsSync(astMapPath)) {
    const raw = JSON.parse(fs.readFileSync(astMapPath, 'utf8'));
    Object.keys(raw).forEach(k => functionMap.set(k, raw[k]));
}

function wrapFunction(relativePath, fnName, fn) {
    const tracer = trace.getTracer('shinkei-auto');

    return function wrapped(...args) {
        return tracer.startActiveSpan(\`\${relativePath} > \${fnName}\`, (span) => {
            const meta = functionMap.get(\`\${relativePath}:\${fnName}\`);

            if (meta) {
                // 🔗 Bridge to Static Analysis
                span.setAttribute('shinkei.static.file', meta.file);
                span.setAttribute('shinkei.static.line', meta.line);
                span.setAttribute('shinkei.static.function', fnName);
            }

            try {
                const result = fn.apply(this, args);

                // Handle async seamlessly
                if (result && typeof result.then === 'function') {
                    return result
                        .then(res => { span.end(); return res; })
                        .catch(err => { span.recordException(err); span.end(); throw err; });
                }

                span.end();
                return result;
            } catch (err) {
                span.recordException(err);
                span.end();
                throw err;
            }
        });
    };
}

function autoWrapExports(relativePath, exports) {
    if (!exports) return exports;

    // Case 1: Object exports (module.exports = { a, b })
    if (typeof exports === 'object') {
        Object.keys(exports).forEach(key => {
            if (typeof exports[key] === 'function' && functionMap.has(\`\${relativePath}:\${key}\`)) {
                exports[key] = wrapFunction(relativePath, key, exports[key]);
            }
        });
    }

    // Case 2: Function export (module.exports = function a() {})
    if (typeof exports === 'function') {
        const name = exports.name || 'default';
        if (functionMap.has(\`\${relativePath}:\${name}\`)) {
            return wrapFunction(relativePath, name, exports);
        }
    }

    return exports;
}

// 🔥 Intercept require()
Module.prototype.require = function (modulePath) {
    const exported = originalRequire.apply(this, arguments);

    try {
        // Ignore native modules and third-party libraries entirely
        if (modulePath.includes('node_modules') || !modulePath.startsWith('.')) {
            return exported;
        }

        // Resolve absolute path to figure out the exact relative path
        const resolvedPath = Module._resolveFilename(modulePath, this, false);
        
        // Only wrap files inside our target repository
        if (resolvedPath.startsWith(repoRoot) && !resolvedPath.includes('node_modules')) {
            // Normalize path to match static analysis index (e.g., 'src/utils.js')
            const relativePath = path.relative(repoRoot, resolvedPath).replace(/\\\\/g, '/');
            return autoWrapExports(relativePath, exported);
        }
    } catch (err) {
        // Silent fail on wrap to not break target app logic
    }

    return exported;
};
console.log('✅ Shinkei Require Hook Active');
`;
// ─── Step 2: Frontend Launcher & Interceptor ─────────────────────────────


async function launchFrontend(repoRoot, options = {}) {

    const candidates = ['frontend', 'client', 'web', 'ui', '.'];

    let frontendPath = null;

    let startCommand = 'npm start';

    const FE_PORT = options.frontendPort || 3000;
    const BE_PORT = options.backendPort || 8000;


    for (const dir of candidates) {

        const checkPath = path.join(repoRoot, dir, 'package.json');

        if (await fs.pathExists(checkPath)) {

            frontendPath = path.join(repoRoot, dir);

            const pkg = await fs.readJson(checkPath);

            if (pkg.scripts && pkg.scripts.dev) startCommand = 'npm run dev';

            break;

        }

    }


    if (!frontendPath) return null;


    // 1. Dependency Check

    const nodeModulesPath = path.join(frontendPath, 'node_modules');

    if (!fs.existsSync(nodeModulesPath)) {

        console.log(`📦 [Shinkei] Installing dependencies in ${frontendPath}...`);

        execSync('npm install --no-audit --no-fund', { cwd: frontendPath, stdio: 'inherit' });

        console.log("✅ [Shinkei] Dependencies installed.");

    }


    // 1. Force the dev server to use our port by appending flags if it's an npm command
    let finalCommand = startCommand;
    if (startCommand.startsWith('npm')) {
        finalCommand = `${startCommand} -- --port ${FE_PORT}`;
    }

    // 2. Prepare Network Interceptor with dynamic hostname support
    const htmlFiles = [
        path.join(frontendPath, 'public', 'index.html'),
        path.join(frontendPath, 'index.html'),
        path.join(frontendPath, 'src', 'index.html')
    ];

    const interceptorScript = `
    <script>
      (function() {
        const BE_PORT = '${BE_PORT}';
        const BACKEND_URL = 'http://' + window.location.hostname + ':' + BE_PORT;
        console.log('💉 [Shinkei] Interceptor Active: Routing API traffic to ' + BACKEND_URL);

        const rewrite = (url) => {
          if (typeof url === 'string' && (url.startsWith('/api') || url.startsWith('api/'))) {
             const normalized = url.startsWith('/') ? url : '/' + url;
             return BACKEND_URL + normalized;
          }
          return url;
        };

        const origFetch = window.fetch;
        window.fetch = (url, init) => origFetch(rewrite(url), init);

        const origOpen = XMLHttpRequest.prototype.open;
        XMLHttpRequest.prototype.open = function(m, url) {
          return origOpen.apply(this, [m, rewrite(url), ...Array.from(arguments).slice(2)]);
        };
      })();
    </script>`;

    for (const file of htmlFiles) {
        if (fs.existsSync(file)) {
            let content = fs.readFileSync(file, 'utf8');
            if (!content.includes('BACKEND_URL')) {
                // Insert before </head> instead of after <head> for better compatibility
                content = content.replace('</head>', interceptorScript + '</head>');
                fs.writeFileSync(file, content);
                console.log("[Shinkei] ✅ Injected Network Interceptor into " + path.basename(file));
            }
        }
    }


    console.log(`🚀 Launching Frontend on PORT ${FE_PORT}...`);

    const child = exec(finalCommand, {
        cwd: frontendPath,
        env: { 
            ...process.env, 
            PORT: FE_PORT, 
            BROWSER: 'none', // 👈 Disable default browser opening by the target app
            REACT_APP_API_URL: `http://localhost:${BE_PORT}`,
            VITE_API_URL: `http://localhost:${BE_PORT}`
        }
    });

    console.log(`⏳ Waiting for frontend to stabilize... will auto-open in 3s.`);

    // 🌐 Automatically open the browser after a short delay
    const openCommand = process.platform === 'win32' ? 'start' : process.platform === 'darwin' ? 'open' : 'xdg-open';
    setTimeout(() => {
        console.log(`🌐 Opening target app at http://localhost:${FE_PORT}...`);
        exec(`${openCommand} http://localhost:${FE_PORT}`);
        
        // 📡 Notify frontend that the app is being opened on its specific port
        sseService.broadcast({ 
            type: 'app_opened', 
            url: `http://localhost:${FE_PORT}` 
        });
    }, 3000);

    child.stdout.on('data', (data) => console.log(`[Target Frontend]: ${data.trim()}`));

    return child;
}


async function getEntryPoint(repoRoot) {

    // 1. Define where backends usually hide

    const searchDirs = [

        repoRoot,

        path.join(repoRoot, 'server'),

        path.join(repoRoot, 'backend'),

        path.join(repoRoot, 'api')

    ];


    for (const dir of searchDirs) {

        if (!await fs.pathExists(dir)) continue;


        const pkgPath = path.join(dir, 'package.json');

        if (await fs.pathExists(pkgPath)) {

            const pkg = await fs.readJson(pkgPath);

            

            // Try 'main'

            if (pkg.main) {

                const mainPath = path.join(dir, pkg.main);

                if (await fs.pathExists(mainPath)) return mainPath;

            }

            

            // Try 'start' script

            if (pkg.scripts?.start) {

                const match = pkg.scripts.start.match(/(?:node|nodemon|ts-node)\s+(.+)/);

                if (match && match[1]) {

                    const found = match[1].trim().split(' ')[0].replace(/['"]/g, '');

                    const fullPath = path.join(dir, found);

                    if (await fs.pathExists(fullPath)) return fullPath;

                }

            }

        }


        // 2. Fallback to common filenames in this specific directory

        const fallbacks = ['index.js', 'app.js', 'server.js', 'src/index.js', 'src/server.js'];

        for (const f of fallbacks) {

            const fullPath = path.join(dir, f);

            if (await fs.pathExists(fullPath)) return fullPath;

        }

    }


    throw new Error("Shinkei could not find a backend entry point. Try adding a 'main' field to your package.json.");

}


// ─── Step 3: Analysis Orchestration ──────────────────────────────────────


let activeProcesses = [];

async function stopActiveProcesses() {
    if (activeProcesses.length === 0) return;
    
    console.log(`🛑 Stopping ${activeProcesses.length} active processes...`);
    for (const proc of activeProcesses) {
        if (proc && !proc.killed) {
            try {
                // On Windows, killing process trees can be tricky with just .kill()
                if (process.platform === 'win32') {
                    execSync(`taskkill /pid ${proc.pid} /f /t`);
                } else {
                    proc.kill('SIGTERM');
                }
            } catch (e) {
                // Ignore if already dead
            }
        }
    }
    activeProcesses = [];
    console.log("✅ All target processes stopped.");
}

async function prepareAndRunDynamicAnalysis(repoRoot, options = {}) {

    try {
        await stopActiveProcesses(); // 👈 Kill old ones before starting new ones
        console.log("🛠️  Preparing Dynamic Tracing Infrastructure...");

        // 🔍 Discover available ports dynamically
        const BE_PORT = await findFreePort(options.backendPort || 8000);
        const FE_PORT = await findFreePort(options.frontendPort || 3000);

        console.log(`📡 Allocated Ports: Backend=${BE_PORT}, Frontend=${FE_PORT}`);

        await fs.writeFile(path.join(repoRoot, "tracing.js"), TRACING_CODE);

        await fs.writeFile(path.join(repoRoot, "requireHook.js"), REQUIRE_HOOK_CODE);


        const astMap = {};

        for (const [relativePath, data] of index.files.entries()) {

            if (data.functions) {

                data.functions.forEach(fn => {

                    const isAnonymous = !fn.name || 

                                        fn.name.startsWith('anonymous_') || 

                                        fn.name === 'anonymous' ||

                                        fn.name.includes('<anonymous>');


                    if (!isAnonymous) {

                        const key = relativePath + ":" + fn.name;

                        astMap[key] = {

                            file: relativePath,

                            line: fn.startLine,

                            name: fn.name

                        };

                    }

                });

            }

        }

        await fs.writeJson(path.join(repoRoot, "ast_map.json"), astMap);


        const globalNodeModules = execSync('npm root -g').toString().trim();

        const entryFile = await getEntryPoint(repoRoot);


        console.log(`🚀 Launching Backend (${entryFile}) on PORT ${BE_PORT}...`);

        const backendCmd = `node --require ./tracing.js --require ./requireHook.js ${entryFile}`;

        

        const backendProcess = exec(backendCmd, { 
            cwd: repoRoot,
            env: { 
                ...process.env, 
                NODE_PATH: globalNodeModules, 
                PORT: BE_PORT, 
                SHINKEI_REPO_ROOT: repoRoot 
            }
        });

        activeProcesses.push(backendProcess); // 👈 Track backend

        const frontendProcess = await launchFrontend(repoRoot, options);
        if (frontendProcess) activeProcesses.push(frontendProcess); // 👈 Track frontend


        backendProcess.stdout.on('data', (data) => console.log(`[Target Backend]: ${data.trim()}`));

        return { backendProcess, frontendProcess };


    } catch (err) {

        console.error("❌ Dynamic setup failed:", err.message);

    }

}


// ─── Utility Exports ─────────────────────────────────────────────────────


async function fetchRepoAsZip(repoUrl, runDynamic = false, options = {}) {

    const { repo } = parseRepoUrl(repoUrl);

    const uniqueId = Date.now();

    

    await fs.ensureDir(TEMP_DIR);

    

    const extractPath = path.join(TEMP_DIR, `${repo}-${uniqueId}`);

    const zipPath = path.join(TEMP_DIR, `${repo}-${uniqueId}.zip`);


    await downloadZip(getZipUrl(repoUrl), zipPath);

    

    const zip = new AdmZip(zipPath);

    zip.extractAllTo(extractPath, true);


    const folders = await fs.readdir(extractPath);

    const repoRoot = path.join(extractPath, folders[0]);


    if (runDynamic) {

        prepareAndRunDynamicAnalysis(repoRoot, options).catch(console.error);

    }

    return repoRoot;

}


function parseRepoUrl(url) {
    try {
        const urlObj = new URL(url);
        const pathParts = urlObj.pathname.split('/').filter(Boolean);
        
        // Handle standard GitHub/GitLab/Bitbucket: /owner/repo
        const owner = pathParts[0] || 'unknown';
        const repo = pathParts[1] ? pathParts[1].replace('.git', '') : 'repo-' + Date.now();
        
        return { 
            host: urlObj.host, 
            hostname: urlObj.hostname,
            owner, 
            repo 
        };
    } catch (e) {
        // Fallback for non-URL strings or local paths
        return { owner: 'local', repo: 'project-' + Date.now() };
    }
}


function getZipUrl(url) {
    const { hostname, owner, repo } = parseRepoUrl(url);
    
    if (hostname.includes('gitlab.com')) {
        return `https://gitlab.com/${owner}/${repo}/-/archive/master/${repo}-master.zip`;
    }
    if (hostname.includes('bitbucket.org')) {
        return `https://bitbucket.org/${owner}/${repo}/get/master.zip`;
    }

    // Default to GitHub
    return `https://github.com/${owner}/${repo}/zipball/master`;
}


async function downloadZip(url, dest) {

    const res = await axios({ method: 'GET', url, responseType: 'stream' });

    const writer = fs.createWriteStream(dest);

    res.data.pipe(writer);

    return new Promise((rs, rj) => { 

        writer.on('finish', rs); 

        writer.on('error', rj); 

    });

}


async function clearTempFolder() {

    if (await fs.pathExists(TEMP_DIR)) {

        await fs.emptyDir(TEMP_DIR);

    }

}


module.exports = { fetchRepoAsZip, clearTempFolder, stopActiveProcesses }; 
