const TRACING_CODE = `
const { NodeSDK } = require('@opentelemetry/sdk-node');
const { getNodeAutoInstrumentations } = require('@opentelemetry/auto-instrumentations-node');
const { OTLPTraceExporter } = require('@opentelemetry/exporter-trace-otlp-http');

const sdk = new NodeSDK({
  traceExporter: new OTLPTraceExporter({
    url: '{{SHINKEI_BACKEND_URL}}/api/shinkei/v1/traces',
  }),
  instrumentations: [
    getNodeAutoInstrumentations({
      '@opentelemetry/instrumentation-fs': { enabled: false }
    })
  ],
  serviceName: 'shinkei-dynamic-target',
});

sdk.start();
console.log('✅ Shinkei OTel SDK Active');
`;

const REQUIRE_HOOK_CODE = `
const Module = require('module');
const { trace } = require('@opentelemetry/api');
const fs = require('fs');
const path = require('path');

const originalRequire = Module.prototype.require;
const repoRoot = process.env.SHINKEI_REPO_ROOT;

// 🔥 Load the AST map generated by Shinkei Static Analysis
const astMapPath = path.join(__dirname, 'ast_map.json');
let functionMap = new Map();
if (fs.existsSync(astMapPath)) {
    const raw = JSON.parse(fs.readFileSync(astMapPath, 'utf8'));
    Object.keys(raw).forEach(k => functionMap.set(k, raw[k]));
}

function wrapFunction(relativePath, fnName, fn) {
    const tracer = trace.getTracer('shinkei-auto');

    return function wrapped(...args) {
        return tracer.startActiveSpan(\`\${relativePath} > \${fnName}\`, (span) => {
            const meta = functionMap.get(\`\${relativePath}:\${fnName}\`);

            if (meta) {
                span.setAttribute('shinkei.static.file', meta.file);
                span.setAttribute('shinkei.static.line', meta.line);
                span.setAttribute('shinkei.static.function', fnName);
            }

            try {
                const result = fn.apply(this, args);
                if (result && typeof result.then === 'function') {
                    return result
                        .then(res => { span.end(); return res; })
                        .catch(err => { span.recordException(err); span.end(); throw err; });
                }

                span.end();
                return result;
            } catch (err) {
                span.recordException(err);
                span.end();
                throw err;
            }
        });
    };
}

function autoWrapExports(relativePath, exports) {
    if (!exports) return exports;

    if (typeof exports === 'object') {
        Object.keys(exports).forEach(key => {
            if (typeof exports[key] === 'function' && functionMap.has(\`\${relativePath}:\${key}\`)) {
                exports[key] = wrapFunction(relativePath, key, exports[key]);
            }
        });
    }

    if (typeof exports === 'function') {
        const name = exports.name || 'default';
        if (functionMap.has(\`\${relativePath}:\${name}\`)) {
            return wrapFunction(relativePath, name, exports);
        }
    }

    return exports;
}

Module.prototype.require = function (modulePath) {
    const exported = originalRequire.apply(this, arguments);

    try {
        if (modulePath.includes('node_modules') || !modulePath.startsWith('.')) {
            return exported;
        }

        const resolvedPath = Module._resolveFilename(modulePath, this, false);
        
        if (resolvedPath.startsWith(repoRoot) && !resolvedPath.includes('node_modules')) {
            const relativePath = path.relative(repoRoot, resolvedPath).replace(/\\\\/g, '/');
            return autoWrapExports(relativePath, exported);
        }
    } catch (err) {}

    return exported;
};
console.log('✅ Shinkei Require Hook Active');
`;

module.exports = { TRACING_CODE, REQUIRE_HOOK_CODE };